### ISSUE TITLE
Process name column allows selecting process with editing disabled

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1875] opened 2024-01-31 11:52 UTC
The insert row functionality of the samplesheet editor gives users the ability to change "Protocol Name" of a process node. These values should be fixed and changing one row would lead to ISA parsing errors.

![grafik](https://github.com/bihealth/sodar-server/assets/29800411/44a1ef1c-a934-4aea-8b62-d657e3bda56a)

**Comment by mikkonie** [comment] 2024-02-01 08:54
This is not a bug. These do not cause parsing errors, unless there is some special case where they do. In that case, please let me know where that happens.

Furthermore, by default, SODAR sets up process columns as uneditable, with the default value being applied being the one already in the existing sheet/template. So by default they already are "fixed". Closing.

**Comment by sellth** [comment] 2024-02-01 09:22
These changes raise `ModerateIsaValidationWarning: Parameter Value "xxx" not declared for Protocol "yyy" in investigation file`. 

Users should not be allowed to edit these cells at all imho as this almost always results in an invalid state. That SODAR does not show the parser warnings after saving the samplesheet is also questionable.

**Comment by mikkonie** [comment] 2024-02-01 10:20
Stop reopening closed tickets.

If you want a ticket to restrict processes to a single value per column, open a feature request for that. I'm all for it, if there are no objections from other expert users. Also name that issue descriptively, "User can make invalid choices during Insert Row" means nothing.

To reiterate once more: with default settings this "issue" does not exist in the first place, as the default (and usually only) value gets autofilled and the user does not get to change anything.

**Comment by mikkonie** [comment] 2024-02-01 11:45
Reopening myself :P It appears there actually is a bug in here. Even though the editing is disabled and a default value set, the choice dropdown for a process cell can be entered.

This definitely should not be and it has definitely worked before. Looking into it.

**Comment by mikkonie** [comment] 2024-02-01 14:20
This is interesting. This only happens with `ObjectSelectEditor` when used on protocol ref columns, while other editors exhibit expected behaviour. The `fieldEditable` value is correctly set to `false` upon initial building of the grid, but the editor still opens. 

I guess this must go wrong somewhere in `enableNextNodes()`. Investigating..

Update: this doesn't look correct at least.

```
// If the next node is a material, enable editing its name
// Else if it's a process, enable editing for all cells (if available)
```

**Comment by mikkonie** [comment] 2024-02-01 15:36
Fixed. That was a braindead developer error, no excuse.

**Closed as completed by mikkonie** 2024-02-01 15:36 UTC
Labels: bug, app: samplesheets
